# Generated by Django 4.0.4 on 2022-06-03 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrarVista',
            fields=[
                ('rutM', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut del dueño')),
                ('nombreVeterinario', models.CharField(max_length=30, verbose_name='Nombre de la Mascota')),
                ('correoM', models.CharField(max_length=30, verbose_name='rut del dueño')),
                ('contrasenaM', models.CharField(max_length=30, verbose_name='contraseña')),
                ('conficontrasenaM', models.CharField(max_length=30, verbose_name='confirmar contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoServicio', models.CharField(max_length=20, verbose_name='Tipo de servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexoAnimal', models.CharField(max_length=20, verbose_name='Sexo del animal')),
            ],
        ),
        migrations.CreateModel(
            name='TipoAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=20, verbose_name='Nombre de la Raza')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroM',
            fields=[
                ('idRegistroM', models.AutoField(primary_key=True, serialize=False, verbose_name='ID auntoincremental de registro')),
                ('nombreDue', models.CharField(max_length=30, verbose_name='nombre del dueño')),
                ('correo', models.CharField(max_length=30, verbose_name='rut del dueño')),
                ('rut', models.CharField(max_length=10, verbose_name='rut del dueño')),
                ('nombreMAS', models.CharField(max_length=20, verbose_name='Nombre mascota')),
                ('raza', models.CharField(max_length=20, verbose_name='Nombre mascota')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forpets.tipoanimal')),
            ],
        ),
    ]
