# Generated by Django 4.0.4 on 2022-06-03 17:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forpets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='atencion',
            fields=[
                ('idAtencion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id atencion')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('diagnostico', models.CharField(max_length=40, verbose_name='diagnostico')),
                ('tratamiento', models.CharField(max_length=40, verbose_name='tratamineto')),
                ('costo', models.IntegerField(max_length=20, verbose_name='Clave Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='dueno',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False, verbose_name='rut del dueño')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre dueño')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido dueño')),
                ('correo', models.CharField(max_length=20, verbose_name='correo dueño')),
                ('telefono', models.IntegerField(max_length=20, verbose_name='nombre dueño')),
            ],
        ),
        migrations.CreateModel(
            name='mascota',
            fields=[
                ('idMascota', models.IntegerField(primary_key=True, serialize=False, verbose_name='id mascota')),
                ('chip', models.IntegerField(max_length=40, verbose_name='tratamineto')),
                ('nombremascota', models.CharField(max_length=40, verbose_name='nombre mascota')),
                ('edad', models.IntegerField(max_length=10, verbose_name='edad mascota')),
            ],
        ),
        migrations.CreateModel(
            name='raza',
            fields=[
                ('idRaza', models.IntegerField(primary_key=True, serialize=False, verbose_name='id raza')),
                ('nombreRaza', models.CharField(max_length=10, verbose_name='nombre raza')),
            ],
        ),
        migrations.CreateModel(
            name='tipo',
            fields=[
                ('idTipo', models.IntegerField(primary_key=True, serialize=False, verbose_name='ide tipo')),
                ('nombretipo', models.CharField(max_length=10, verbose_name='nombre raza')),
            ],
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('idTipoUsurio', models.IntegerField(primary_key=True, serialize=False, verbose_name='codigo de usuario')),
                ('nombreTipoUsuario', models.CharField(max_length=20, verbose_name='Tipo de usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.IntegerField(primary_key=True, serialize=False, verbose_name='id usuario')),
                ('NombreUsuario', models.CharField(max_length=30, verbose_name='Nombre usuario')),
                ('rutUsuario', models.CharField(max_length=11, verbose_name='Rut usuario')),
                ('CorreoUsurio', models.CharField(max_length=40, verbose_name='Correo Usuario')),
                ('ClaveUsuario', models.CharField(max_length=20, verbose_name='Clave Usuario')),
                ('IdRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forpets.tipousuario')),
            ],
        ),
        migrations.DeleteModel(
            name='RegistrarVista',
        ),
        migrations.RemoveField(
            model_name='registrom',
            name='animal',
        ),
        migrations.DeleteModel(
            name='Servicios',
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
        migrations.DeleteModel(
            name='RegistroM',
        ),
        migrations.DeleteModel(
            name='TipoAnimal',
        ),
        migrations.AddField(
            model_name='raza',
            name='idTipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forpets.tipo'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='idRaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forpets.raza'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forpets.dueno'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forpets.usuario'),
        ),
    ]
