# Generated by Django 4.0.4 on 2022-06-07 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forpets', '0002_atencion_dueno_mascota_raza_tipo_tipousuario_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='dueno',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='chip',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='idRaza',
        ),
        migrations.DeleteModel(
            name='raza',
        ),
        migrations.DeleteModel(
            name='tipo',
        ),
    ]
